#!/usr/bin/env bash
# Materialise a new evolution trial as its own git repo.
#
#   ./start-trial.sh 2026-08-09-t3            # all graded problems
#   ./start-trial.sh 2026-08-09-t3 01 03      # a subset
#
# A trial is a REPO, not a directory in the rig. It gets its own COPY of `kda`
# and `swarm`, and pins the bench as a submodule.
#
# Copies, not submodules, for two reasons. A copy makes the trial portable —
# push it anywhere and everything resolves, which a local-path submodule cannot
# do. And a trial can patch its own harness mid-run without changing the
# starting line for every later trial; both earlier trials did exactly that.
# Provenance is the rig SHA recorded in TRIAL.md rather than a submodule
# pointer, and a controlled comparison still works: check the rig out at an
# older SHA and start the trial from there (see ../plan.md §2).
#
# It does NOT ship contracts. Rule 2's work model and the contract itself are
# derived by the trial in its first cycle, from the bench plus the playbook's
# machine section. Handing them over would give every future trial a correction
# for free and nobody would learn whether the loop can derive it.
#
# The venv is SHARED, by symlink: the bench is 58 MB of git and 4.7 GB of
# `.venv`, so N trials cost N x 58 MB. The cost is that all trials must agree on
# dependencies; two bench SHAs with different `uv.lock` cannot share one venv.
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
rig=$(cd "$here/.." && pwd)
runs=${CB_RUNS:-$HOME/evo-runs}
rigbench=${CB_RIG_BENCH:-$rig/kernelbench.com}
deck=${CB_DECK:-problems-rtx2070}

name=${1:?usage: ./start-trial.sh <trial-name> [NN ...]}
shift || true
dest="$runs/$name"
[ -e "$dest" ] && { echo "start-trial.sh: $dest already exists" >&2; exit 2; }
[ -d "$rigbench/benchmarks/cuda/$deck" ] || { echo "start-trial.sh: no deck at $rigbench/benchmarks/cuda/$deck" >&2; exit 2; }

sub() { git -c protocol.file.allow=always submodule add -q "$@"; }   # file:// is blocked by default (CVE-2022-39253)

if [ $# -gt 0 ]; then picks=("$@"); else
  picks=(); for d in "$rigbench/benchmarks/cuda/$deck"/*/; do picks+=("$(basename "$d" | cut -d_ -f1)"); done
fi

mkdir -p "$dest" && cd "$dest" && git init -q

echo "  copying method and apparatus..."
cp "$rig/KDA.md" KDA.md
cp -r "$rig/swarm" swarm
rm -rf swarm/.git
cp "$here/template/SWARM.md" SWARM.md

echo "  pinning the bench..."
sub "$rigbench" kernelbench.com
# Clone from the local checkout (fast, no network) but RECORD its real remote, so
# the trial resolves from anywhere it is pushed. A local path here is what made
# the first pushed trial unclonable.
kda_agents=${CB_KDA_AGENTS:-$rig/kernel-design-agents}
if [ -d "$kda_agents" ]; then
  agents_url=$(git -C "$kda_agents" config --get remote.origin.url || echo "$kda_agents")
  sub "$kda_agents" kernel-design-agents
  git config -f .gitmodules submodule.kernel-design-agents.url "$agents_url"
  echo "  kernel-design-agents -> $agents_url"
fi

bench_url=$(git -C "$rigbench" config --get remote.origin.url || true)
bench_branch=$(git -C "$rigbench" rev-parse --abbrev-ref HEAD || echo master)
if [ -n "$bench_url" ]; then
  git config -f .gitmodules submodule.kernelbench.com.url "$bench_url"
  git config -f .gitmodules submodule.kernelbench.com.branch "$bench_branch"
  git submodule sync -q
  echo "  bench url -> $bench_url ($bench_branch)"
fi

venv="$rigbench/benchmarks/cuda/.venv"
if [ -d "$venv" ]; then
  ln -s "$venv" "kernelbench.com/benchmarks/cuda/.venv"
  # Exclude it INSIDE the submodule, via its own .git/info/exclude rather than the
  # bench's tracked .gitignore -- editing anything under kernelbench.com is
  # bench-rule-forbidden. Without this the symlink shows as untracked content, the
  # rig sees the submodule as modified, and gpu.sh's integrity guard aborts every run.
  echo "benchmarks/cuda/.venv" >> "$(git -C kernelbench.com rev-parse --git-dir)/info/exclude"
  echo "  .venv -> shared ($(du -sh "$venv" 2>/dev/null | cut -f1)), excluded locally"
fi

cat > .gitignore <<'EOF'
# Per-candidate run logs (regenerate with swarm/harness/run.sh)
*/runs/

# Nsight Compute binaries — several MB each. The hand-written REPORT.md next to
# each one stays tracked: for the runs that rejected a change it is the only
# place the reasoning lives.
*/profile/*/*.ncu-rep

# Python bytecode from tools/ run in place
*/tools/__pycache__/

# Generated by swarm/harness/timeline.py
timeline.html

# The shared venv, symlinked in by start-trial.sh
kernelbench.com/benchmarks/cuda/.venv
EOF

for nn in "${picks[@]}"; do
  src=$(echo "$rigbench/benchmarks/cuda/$deck/${nn}_"*)
  [ -d "$src" ] || { echo "start-trial.sh: no problem $nn in $deck" >&2; exit 2; }
  slug=$(basename "$src" | sed "s/^${nn}_//; s/_/-/g")
  t="$nn-$slug"
  # Seed only what a trial demonstrably keeps. Measured across t2's four tasks:
  # collect.py survived 4/4 unchanged and HYPOTHESES.md grew 36 -> 223-314 lines,
  # while smoke.py was rewritten 4/4, docs/ was untouched 8/8, and prof_driver.py
  # was rewritten by three tasks -- the one task that kept it is the one that
  # silently profiled the wrong shape for a whole cycle (playbook rule 28).
  # A stub that is always rewritten except when it poisons a task is worse than
  # no stub. runs/ and profile/ are created by the harness that writes them.
  # A task starts with FIVE files and no directories. Everything dropped was
  # measured on trial 2: config.json was read by no code and left at its stub by
  # 4/4; collect.py was kept byte-identical by 4/4, so it belongs in the harness
  # rather than copied per task; smoke.py and prof_driver.py were rewritten by
  # 4/4 and 3/4, and the one task that kept prof_driver.py profiled the wrong
  # shape for a whole cycle. tools/, candidates/, runs/ and profile/ are created
  # by whoever first writes into them -- git does not track empty directories.
  # HYPOTHESES.md is gone too: hypotheses are entries in the log, and the open set
  # is DERIVED by `status.sh --open` rather than asserted in a hand-kept list that
  # nothing forces to stay true.
  mkdir -p "$t"

  # The three documents a worker needs, all reachable without leaving its own
  # directory: what the task is, how to optimise a kernel, how to work in the
  # swarm. The last two are symlinks -- one source of truth, no drift between
  # four copies, and a worker that reads ./KDA.md still gets the real thing.
  {
    printf '# %s — the task\n\n' "$t"
    printf 'Verbatim from `kernelbench.com/benchmarks/cuda/%s/%s_*/PROMPT.txt` at the\n' "$deck" "$nn"
    printf 'pinned bench commit. The scoring rules, shapes and tolerances live beside it in\n'
    printf '`problem.yaml`, `shapes.py`, `check.py` and `benchmark.py` — read those too, and\n'
    printf 'trust them over anything summarised here.\n\n'
    printf 'Then read `KDA.md` for how to attack it and `SWARM.md` for how to work alongside\n'
    printf 'the other three workers.\n\n---\n\n'
    cat "$src/PROMPT.txt" 2>/dev/null || printf '(no PROMPT.txt in the problem directory)\n'
  } > "$t/prompt.md"
  ln -s ../KDA.md "$t/KDA.md"
  ln -s ../SWARM.md "$t/SWARM.md"
  : > "$t/candidates.jsonl"
  sed "s/^# TASKNAME — log$/# $t — log/" "$here/template/STATUS.md" > "$t/STATUS.md"
  cat >> "$t/STATUS.md" <<EOF

### bootstrap · \`note\`

Seeded by \`start-trial.sh\`. Nothing here is measured yet.

**What you were given** — this log, an empty \`candidates.jsonl\`, and the three documents
beside them: \`prompt.md\`, \`KDA.md\`, \`SWARM.md\`. Five files, no directories. That is all,
deliberately.

**What you must write** — everything else, in playbook rule 10's order:

1. \`CONTRACT.md\` — transcribe from \`kernelbench.com/benchmarks/cuda/$deck/${nn}_*/\`
   (\`PROMPT.txt\`, \`problem.yaml\`, \`shapes.py\`, \`check.py\`, \`benchmark.py\`),
   inventing nothing (rule 1).
2. The **hand-counted work model** into \`CONTRACT.md\`, before any candidate (rule 2) —
   executed FLOPs and bytes per shape, arithmetic intensity, which roof binds, the floor
   in ms. Do not take the numerator from \`problem.yaml\`; on this deck its formulas were
   wrong in every way available.
3. A **ground truth** the reference is validated against — slow, obvious, independent.
4. A **broken kernel** that \`check.py\` is shown to FAIL (rule 4), and a \`smoke.py\`
   covering the shapes \`check.py\` does not.
5. Only then, the first candidate.

**No \`prof_driver.py\` is provided, and that is on purpose.** The shared one used to
select a shape with problem 03's knob; three tasks rewrote it and the fourth silently
profiled the wrong shape for a whole cycle. Write your own, validate the selector against
the real graded list, and \`sys.exit\` on a miss — playbook rule 28.

**Hypothesis** — none yet.
**Result** — nothing measured.
**Notes** — no contract, no candidates, no measurements. Start at 1.
EOF
  echo "  seeded $t"
done

rig_sha=$(git -C "$rig" rev-parse --short HEAD)
bench_sha=$(git -C kernelbench.com rev-parse --short HEAD)

cat > env.sh <<EOF
# source this before using swarm/harness — it points the harness at THIS trial's
# pinned bench rather than the rig's checkout.
export CB_BENCH_CUDA="$dest/kernelbench.com/benchmarks/cuda"
export CB_WT_ROOT="\${CB_WT_ROOT:-$dest-wt}"
EOF

cat > TRIAL.md <<EOF
# Trial $name

Started $(date -Is). A trial does not end: a leader session resumes it and keeps
optimising. Each task's \`STATUS.md\` is an append-only log, which is what makes that
possible.

## Pinned inputs

| | |
| --- | --- |
| tasks | ${picks[*]} |
| \`KDA.md\`, \`swarm/\` | copied from the rig at \`$rig_sha\` — method and apparatus |
| \`kernel-design-agents\` | submodule — upstream reference material |
| \`kernelbench.com\` | submodule \`$bench_sha\` — **the comparison instrument** |
| contracts | none shipped; the trial writes its own (rule 1, then rule 2) |

\`KDA.md\` and \`swarm/\` are **copies**, so this trial can patch its own harness without
touching any other trial — and a controlled comparison is still available: check the rig
out at an older SHA and start a trial from there, and the knowledge variable is held
fixed. Record here if you deliberately started from an older rig.

## What this trial is testing

<!-- Fill this in before the first cycle. "Can it get faster" is not a hypothesis.
     Pre-register predictions here, with what would falsify them. A prediction written
     after the measurement is a story. -->

## How results are read

Rank on **milliseconds against the hand-counted floor**, not \`peak_fraction\`. Every known
defect in the bench lives in a denominator — see ../plan.md §2.2 and \`KERNELBENCH.md\`.

## Log

<!-- Pre-registrations and results accumulate here. Since the trial does not end, this is
     a register rather than a paper: append, never rewrite. -->
EOF

git add -A
git -c user.name="${GIT_AUTHOR_NAME:-$(git -C "$rig" config user.name)}" \
    -c user.email="${GIT_AUTHOR_EMAIL:-$(git -C "$rig" config user.email)}" \
    commit -q -m "trial $name: seeded from rig@$rig_sha bench@$bench_sha

No contracts and no candidates: the trial derives its own. Tasks ${picks[*]}."

echo
echo "trial ready: $dest"
echo "  rig@$rig_sha (kda + swarm copied)  bench@$bench_sha"
echo
echo "next:"
echo "  1. fill in TRIAL.md's 'what this trial is testing'"
echo "  2. register it in the rig:"
echo "       git -C $rig -c protocol.file.allow=always submodule add $dest trials/$name"
echo "  3. source $dest/env.sh, then /loop /evolve"
